### PR TITLE
Update react-native lib and project to v0.17

### PR DESCRIPTION
**Pull request by nikolaseu**

### CODE REVIEW

**Comment by chirag04** [comment]
Can we merge this? Trying to add lock-android to rn v.17. 

@hzalaz

**Comment by chirag04** [comment]
@hzalaz Thanks. Can you publish on maven/jcentral also?

**Comment by hzalaz** [comment]
I'll do it tomorrow EOD cause I wan to see if I can squeeze something else in the release

**Comment by chirag04** [comment]
sure. Thanks :+1:

**Pull request merged**
